sudo: false
arch:
  - arm64
  - amd64
addons:
  apt:
    packages:
    - rabbitmq-server
language: ruby
rvm:
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - 2.4.1
services:
  - rabbitmq
  - redis
env:
  - RACK_ENV=development
before_install:
  - gem install bundler --version 1.15.1
